name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main # Trigger deployment on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the appropriate Node.js version

      # Step 3: Install Amplify CLI
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      # Step 4: Configure AWS Credentials
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 5: Initialize Amplify environment (if it doesn't exist)
      - name: Initialize Amplify Environment
        run: |
          amplify env list | grep "dev" || amplify env add \
            --name dev \
            --awsRegion ${{ secrets.AWS_REGION }} \
            --yes

      # Step 6: Push environment and deploy
      - name: Deploy to AWS Amplify
        run: amplify push --yes
